name: vsc_tasks_json
version: 1.0.0
description: MCP server for VSCode tasks.json

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  dart_mcp: ^0.3.3
  path: ^1.9.1
  stream_channel: ^2.1.4
  meta: ^1.16.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  lints: ^6.0.0
  freezed: ^3.2.3
  build_runner: ^2.5.2
  json_serializable: ^6.10.0
  test: ^1.25.0

executables:
  mcp:
